import './globals.css'
import ModalPopup from '@/components/ModalPopup'

export const metadata = {
	title: 'Trello 2.0 Clone',
	description: 'Generated by create  app trello Clone',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className="bg-[#f5f6f8]">
				{children}
				<ModalPopup />
			</body>
		</html>
	)
}
